### ISSUE TITLE
How is a non-default memory index to be denoted in the text format?

### ISSUE THREAD

**Issue by lars-t-hansen** [WebAssembly/multi-memory#17]
The context is [this comment](https://github.com/bytecodealliance/wasm-tools/pull/196#issuecomment-762433132).  Currently wasm-tools will accept a memory index denoted simply by an integer trailing the opcode.  This conflicts with the SIMD spec, which wants an integer trailing the opcode to denote a vector lane in some contexts; for instructions with both a memory operand and a lane operand the conflict must be resolved.

I can't find anything in the proposal or interpreter here about what the present proposal thinks is a reasonable way of denoting the memory index in the text format.

Similarly to offset and alignment, may we assume that a keyword must be used, eg memory=n or memidx=n?  @rossberg, opinions?

**Comment by rossberg** [comment]
Segments use `(memory $i)` and `(table $i)`, respectively. Similarly, various references to types use `(type $i)`. So `(memory $i)` seems like the best choice here.

That would also extend nicely to some future syntactic sugar for aliases that we have been converging on for the module linking proposal (e.g., WebAssembly/module-linking#19).

**Comment by rossberg** [comment]
This has been resolved in the recent merge from upstream (#26). Turns out there isn't actually a conflict, and using a plain index is much simpler in terms of the yacc grammar.

We could still consider allowing explicitly tagged references, but then I'd be inclined to consistently allow them in all similar places, which is a bigger change.

**Comment by rossberg** [comment]
Closing as resolved.
