### ISSUE TITLE
Implementation support

### ISSUE THREAD

**Issue by eqrion** [WebAssembly/multi-memory#47]
SpiderMonkey has [implemented](https://bugzilla.mozilla.org/show_bug.cgi?id=1782585) the proposal and it should be available in Nightly builds of Firefox starting on July 8th. You will need to add a preference flag for `javascript.options.wasm_multi_memory` in about:config. If anyone runs into issues, please file bugs [here](https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=JavaScript%3A+WebAssembly).

**Comment by fitzgen** [comment]
Wasmtime has had support for a while now.

To enable it:

* In the CLI: `--wasm-features=multi-memory`
* In the API: [`wasmtime::Config::wasm_multi_memory`](https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.wasm_multi_memory)

[Report issues here](https://github.com/bytecodealliance/wasmtime/issues/new?assignees=&labels=bug&projects=&template=wasmtime-bug-report.md&title=)

**Comment by backes** [comment]
V8's implementation is also feature complete and we put some effort into reasonable performance already (there shouldn't be a noticable difference between different memory indexes).
It's available since V8 v11.7.428 or Chromium 117.0.5936.0.

To enable
- in V8: pass `--experimental-wasm-multi-memory` or `--wasm-staging`
- in Chromium: Enable `Experimental WebAssembly` in `chrome://flags`

Report issues (correctness of performance) in [V8's bug tracker](https://crbug.com/v8/new).

**Comment by conrad-watt** [comment]
With two feature-complete Web implementations, we seem to have satisfied the implementation part of the phase 4 [requirements](https://github.com/WebAssembly/meetings/blob/main/process/phases.md#4-standardize-the-feature-working-group). Is there a place where we can track progress on the other requirements?

**Comment by ashleynh** [comment]
There is now! #50
